name: '@nativescript/template-* -> npm'

on:
  push:
    branches: [ 'main' ]

env:
  NPM_TAG: 'next'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: npm install

      - name: Publish All Templates
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          # run publish in every package, ignore failures (ie no publish required if the version is already published)
          npm run prepare-templates
          npx lerna exec --no-bail --stream --concurrency 1 -- "cp ../../.npmrc . && (npm publish || true)"
